name: 'Compile and run tests'
description: 'Compiles and runs homework tests'
inputs:
  task_name:
    description: 'Task name'
    required: true
  test_file:
    description: 'Test file'
    required: true
  test_to_run:
    description: 'Name of test that should be run'
  pattern_lcov:
    description: 'Regex for searching homework file in lcov report'
  pattern_template:
    description: 'Regex for template initialization'
runs:
  using: 'composite'
  steps:
    - run: sudo apt install lcov
      shell: bash
    - name: Run tests and sanitizer
      uses: ./.github/actions/run_tests
      with:
        task_name: ${{ inputs.task_name }}
        test_file: ${{ inputs.test_file }}
        test_to_run: ${{ inputs.test_to_run }}
    - run: $GITHUB_ACTION_PATH/check_coverage.sh "${{ inputs.test_file }}" "${{ inputs.pattern_lcov }}" "${{ inputs.pattern_template }}"
      shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Coverage-report
        path: ./.github/scripts/build/report/
    - name: Add comment with coverage info
      uses: ./.github/actions/coverage-rate-comment
        with: 'https://hook.integromat.com/r2dowpjpogyhlt7q825cnk9vc2b741hv'
      if: ${{ failure() && github.event_name == 'pull_request' }}
