

on: [push, pull_request]

jobs:
  ctest:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master

    - name: Create build folder
      working-directory: homework/unique_ptr
      run: mkdir build
    - name: Compile
      working-directory: homework/unique_ptr/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: homework/unique_ptr/build
      run: ctest -V
  valgrind:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master

    - name: Create build folder
      working-directory: homework/unique_ptr
      run: mkdir build
    - name: Compile
      working-directory: homework/unique_ptr/build
      run: |
        cmake ..
        make
    - name: Install and run valgrind
      working-directory: homework/unique_ptr/build
      run: |
        sudo apt-get update && sudo apt-get install valgrind
        valgrind --leak-check=full ./tests
